[package]
name = "xeditor"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["highlighter", "tokio"] }
rfd = "0.17.2"
tokio = { version = "1.49.0", features = ["full"] }
